### ISSUE TITLE
When will the dataset be available

### ISSUE THREAD

**Issue by Aaronchm** [jedaiproject/Open-Source-Event-Driven-ECG-Dataset#1]
Hi,

We saw the publication on TBioCAS **_Evaluation of Level-Crossing ADCs for Event-Driven ECG Classification_** and are very interested in the LC-sampled ECG dataset. Could you please give an estimated date of the dataset being available?

**Comment by jedaiproject** [comment]
Hi. Thank you for waiting. The dataset is now available. If you have any issues, please let me know.
